In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

In [3]:
Avviation = pd.read_csv('AviationData.csv', encoding='latin-1');
Avviation.head(7).T

C:\Users\Ago\anaconda3\envs\learn-env\lib\site-packages\IPython\core\interactiveshell.py:3145: DtypeWarning: Columns (6,7,28) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,0,1,2,3,4,5,6
Event.Id,20001218X45444,20001218X45447,20061025X01555,20001218X45448,20041105X01764,20170710X52551,20001218X45446
Investigation.Type,Accident,Accident,Accident,Accident,Accident,Accident,Accident
Accident.Number,SEA87LA080,LAX94LA336,NYC07LA005,LAX96LA321,CHI79FA064,NYC79AA106,CHI81LA106
Event.Date,1948-10-24,1962-07-19,1974-08-30,1977-06-19,1979-08-02,1979-09-17,1981-08-01
Location,"MOOSE CREEK, ID","BRIDGEPORT, CA","Saltville, VA","EUREKA, CA","Canton, OH","BOSTON, MA","COTTON, MN"
Country,United States,United States,United States,United States,United States,United States,United States
Latitude,NaN,NaN,36.9222,NaN,NaN,42.4453,NaN
Longitude,NaN,NaN,-81.8781,NaN,NaN,-70.7583,NaN
Airport.Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Airport.Name,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Injury.Severity,Fatal(2),Fatal(4),Fatal(3),Fatal(2),Fatal(1),Non-Fatal,Fatal(4)
Aircraft.damage,Destroyed,Destroyed,Destroyed,Destroyed,Destroyed,Substantial,Destroyed
Aircraft.Category,NaN,NaN,NaN,NaN,NaN,Airplane,NaN
Registration.Number,NC6404,N5069P,N5142R,N1168J,N15NY,CF-TLU,N4988E
Make,Stinson,Piper,Cessna,Rockwell,Cessna,Mcdonnell Douglas,Cessna
Model,108-3,PA24-180,172M,112,501,DC9,180
Amateur.Built,No,No,No,No,No,No,No
Number.of.Engines,1,1,1,1,NaN,2,1
Engine.Type,Reciprocating,Reciprocating,Reciprocating,Reciprocating,NaN,Turbo Fan,Reciprocating
FAR.Description,NaN,NaN,NaN,NaN,NaN,Part 129: Foreign,NaN
Schedule,NaN,NaN,NaN,NaN,NaN,SCHD,NaN
Purpose.of.flight,Personal,Personal,Personal,Personal,Personal,NaN,Personal
Air.carrier,NaN,NaN,NaN,NaN,NaN,Air Canada,NaN
Total.Fatal.Injuries,2,4,3,2,1,NaN,4
Total.Serious.Injuries,0,0,NaN,0,2,NaN,0
Total.Minor.Injuries,0,0,NaN,0,NaN,1,0
Total.Uninjured,0,0,NaN,0,0,44,0
Weather.Condition,UNK,UNK,IMC,IMC,VMC,VMC,IMC
Broad.phase.of.flight,Cruise,Unknown,Cruise,Cruise,Approach,Climb,Unknown
Report.Status,Probable Cause,Probable Cause,Probable Cause,Probable Cause,Probable Cause,Probable Cause,Probable Cause
Publication.Date,NaN,19-09-1996,26-02-2007,12-09-2000,16-04-1980,19-09-2017,06-11-2001

In [11]:
mean_mode_values = {
    'Total.Uninjured': Avviation['Total.Uninjured'].mean(),
    'Total.Minor.Injuries': Avviation['Total.Minor.Injuries'].mean(),
    'Total.Serious.Injuries': Avviation['Total.Serious.Injuries'].mean(),
    'Total.Fatal.Injuries': Avviation['Total.Fatal.Injuries'].mean(),
    'Purpose.of.flight':Avviation['Purpose.of.flight'].mode()[0],
    'Air.carrier':Avviation['Air.carrier'].mode()[0],
    'Aircraft.Category':Avviation['Aircraft.Category'].mode()[0],
    'FAR.Description':Avviation['FAR.Description'].mode()[0],
    'Schedule':Avviation['Schedule'].mode()[0],
    'Air.carrier':Avviation['Air.carrier'].mode()[0],
    'Broad.phase.of.flight':Avviation['Broad.phase.of.flight'].mode()[0],
    'Engine.Type':Avviation['Engine.Type'].mode()[0],
    'Number.of.Engines':int(Avviation['Number.of.Engines'].mean()),
    'Weather.Condition':Avviation['Weather.Condition'].mode()[0],
    'Airport.Code':Avviation['Airport.Code'].mode()[0],
    'Airport.Name':Avviation['Airport.Name'].mode()[0],
    'Aircraft.damage':Avviation['Aircraft.damage'].mode()[0],
    'Injury.Severity':Avviation['Injury.Severity'].mode()[0],
    'Make':Avviation['Make'].mode()[0],
    'Amateur.Built':Avviation['Amateur.Built'].mode()[0],
    'Model':Avviation['Model'].mode()[0],
    'Report.Status':Avviation['Report.Status'].mode()[0],
    'Registration.Number':Avviation['Registration.Number'].mode()[0],
    'Country':Avviation['Country'].mode()[0],
    'Location':Avviation['Location'].mode()[0]
}
Avviation.fillna(value=mean_mode_values, inplace=True)
# cleaning data and replaing the data with the relavent method for object's and numerics 
# replacing mean for numerical null values and mode for object types

In [12]:
Avviation.isna().sum()

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                      0
Country                       0
Latitude                  54507
Longitude                 54516
Airport.Code                  0
Airport.Name                  0
Injury.Severity               0
Aircraft.damage               0
Aircraft.Category             0
Registration.Number           0
Make                          0
Model                         0
Amateur.Built                 0
Number.of.Engines             0
Engine.Type                   0
FAR.Description               0
Schedule                      0
Purpose.of.flight             0
Air.carrier                   0
Total.Fatal.Injuries          0
Total.Serious.Injuries        0
Total.Minor.Injuries          0
Total.Uninjured               0
Weather.Condition             0
Broad.phase.of.flight         0
Report.Status                 0
Publication.Date          13771
dtype: int64

In [13]:
Avviation.drop(columns=['Latitude','Longitude','Publication.Date'],inplace=True) 
# dropping long and lat as there are geographical points can't be replaced with randome values
# other reason for droping is there null percentage is more

In [14]:
Avviation.isna().sum()

Event.Id                  0
Investigation.Type        0
Accident.Number           0
Event.Date                0
Location                  0
Country                   0
Airport.Code              0
Airport.Name              0
Injury.Severity           0
Aircraft.damage           0
Aircraft.Category         0
Registration.Number       0
Make                      0
Model                     0
Amateur.Built             0
Number.of.Engines         0
Engine.Type               0
FAR.Description           0
Schedule                  0
Purpose.of.flight         0
Air.carrier               0
Total.Fatal.Injuries      0
Total.Serious.Injuries    0
Total.Minor.Injuries      0
Total.Uninjured           0
Weather.Condition         0
Broad.phase.of.flight     0
Report.Status             0
dtype: int64

In [17]:
duplicateRows = Avviation[Avviation.duplicated()]
print(duplicateRows)

Empty DataFrame
Columns: [Event.Id, Investigation.Type, Accident.Number, Event.Date, Location, Country, Airport.Code, Airport.Name, Injury.Severity, Aircraft.damage, Aircraft.Category, Registration.Number, Make, Model, Amateur.Built, Number.of.Engines, Engine.Type, FAR.Description, Schedule, Purpose.of.flight, Air.carrier, Total.Fatal.Injuries, Total.Serious.Injuries, Total.Minor.Injuries, Total.Uninjured, Weather.Condition, Broad.phase.of.flight, Report.Status]
Index: []

[0 rows x 28 columns]